### ISSUE TITLE
For Premiere Pro, an incorrect MXI file is created

### ISSUE THREAD

**Issue by Rhuagh** [fcamarlinghi/grunt-cep#10]
When building a package for Premiere Pro CC 2015, the MXI file created is not valid. The Adobe Exchange and the ExManCmd commandline utility will reject the created zxp because of it.

The problem is the following: 

                <product familyname="Premiere" maxversion="9.9" primary="true" version="9.0" />

familyname only works for some Adobe products it seems. To make this install in Premiere, it should use the 'name' attribute. I.E. this installs:

                <product name="Premiere" maxversion="9.9" primary="true" version="9.0" />

**Comment by fcamarlinghi** [comment]
Thanks for reporting the issue and sorry if I didn't get back to you sooner.

You're definitely right, after searching through the [official documentation](https://helpx.adobe.com/extension-manager/kb/general-mxi-elements.html#id_64891) it seems that *familyname* is only supported by Photoshop, Illustrator, InDesign and InCopy. I just published a **familyname_fix** branch, but unfortunately I only have Photoshop installed right now, so I'm unable to test it with Premiere. Can you please check if the issue is fixed?

**Comment by Rhuagh** [comment]
No, it doesn't unfortunately. This fixes it though:

         for (var product in product_versions)
         {
-            if (familyname_products.indexOf(familyname_products))
+            if (familyname_products.indexOf(cep.hosts.getProduct(product).familyname.toLowerCase()) > -1)
             {
                 data.products.push('<product familyname="' + cep.hosts.getProduct(product).familyname + '" maxversion="' + product_versions[product].max + '" primary="true" version="' + product_versions[product].min + '" />');
             }
             else
             {
-                data.products.push('<product name="' + cep.hosts.getProduct(product).name + '" maxversion="' + product_versions[product].max + '" primary="true" version="' + product_versions[product].min + '" />');
+                data.products.push('<product name="' + cep.hosts.getProduct(product).familyname + '" maxversion="' + product_versions[product].max + '" primary="true" version="' + product_versions[product].min + '" />');
             }
         }

**Comment by Rhuagh** [comment]
name needs to be "Premiere", but the product name in hosts.json needs to be "Premiere Pro" for the code to find the correct directory in launch mode.

**Comment by Rhuagh** [comment]
No, unfortunately it doesn't work. I submitted a pull request on that branch that should fix it though.

**Comment by fcamarlinghi** [comment]
By looking at it now, I don't know what I was thinking when I wrote that code. :/

Thanks for the PR. Just a consideration about it as I think the following:
```js
familyname_products.indexOf(cep.hosts.getProduct(product).familyname.toLowerCase()) > -1
```
can safely be replaced with:
```js
familyname_products.indexOf(product) > -1
```
as *product* and *cep.hosts.getProduct(product).familyname.toLowerCase()* should always be the same. I installed Premiere and tested the above, and everything seem to be working fine (you can find the changes in the *familyname_fix* branch).

Please let me know if you bump into any problem, I will close your PR but leave this issue open for the moment.

**Comment by Rhuagh** [comment]
Sounds good!
