### ISSUE TITLE
Building zxp for Indesign 2018 on Windows will not be running well on Mac

### ISSUE THREAD

**Issue by Lilipi** [fcamarlinghi/grunt-cep#23]
Hello,
On older versions of Indesign (2017), I built my zxp on my Windows, and it worked well on both Indesign Mac and Windows.
With Indesign 2018, it doesn't : 

- if I build zxp on my windows, it works on Indesign 2018 windows but not mac (white screen and do nothing) (grunt-cep 0.4.4 and 0.4.3)

- if I build it on mac, it works on Indesign 2018 mac and it seems to work on windows too ! (grunt-cep 0.4.4 because cannot build it on mac on 0.4.3 see zxp-provider last release)

Furthermore with the new version of grunt-cep, I have this problem for Indesign 2017 too : 

- if I build zxp on mac, it works on Indesign 2017 in both windows and mac 

- if I build it on windows, it doesn't work on Indesign 2017 windows neither mac (grunt-cep 0.4.4 but worked with grunt-cep 0.4.3)

Any idea ?

Thanks !

**Comment by Lilipi** [comment]
It seems that it's a problem with zxp-provider (from 1.1.2 to 1.1.3)
With grunt-cep 0.4.4 and zxp-provider 1.1.2 : 

- Build for Indesign 2017 on windows works on Windows and Mac
- Build for Indesign 2018 on windows works on Windows and Mac 
- Cannot build on Mac

**Comment by Lilipi** [comment]
Ok, it was my fault.
I've updated node to the last version on my windows and it works !

**Comment by fcamarlinghi** [comment]
Glad to hear you got it fixed! Have a nice day.
