### ISSUE TITLE
Packaging not working since adobe extension manager update

### ISSUE THREAD

**Issue by Lilipi** [fcamarlinghi/grunt-cep#26]
Hello,
Since last Adobe Extension Manager update (22 March 2018), zxp generated by grunt-cep cannot be installed : 
`Installation failed because the extension does not contain a valid code signature.`

I found this release note : 
https://helpx.adobe.com/extension-manager/release-note/extension-manager-cc-release-notes.html

And in particular those points : 

- For hybrid extensions, the MXI file must set "file-type" to "CSXS" for all embedded CEP extensions
- For hybrid extensions, Extension Manager CC only validates the signature of the outer extension. The signature of an embedded CEP extension is not validated

Any idea ?
Thanks

**Comment by fcamarlinghi** [comment]
Hello, I was under the impression that Adobe ceased development and support for Extension Manager in 2015, as announced [here](https://web.archive.org/web/20170214202449/http://www.adobeexchange.com/resources/27) (link is from the Wayback Machine as the original page seem to have gone down).

Did that change recently? If that is the case, can you please provide a download link to the updated version?

**Comment by Lilipi** [comment]
Thanks for you response.
I think Adobe Extension Manager is not available for user for installation.
But, I think they use it as a cloud application to valide packages isn't it ?

I've changed nothing but now I cannot package anymore : 
```
Creating ZXP package at staging\package\a91a126f-8478-400c-9c8b-a7e07d590092.zxp...ERROR
Error - Certificate is expired or not yet valid. Please check certificate validity.

Fatal error: Unable to create ZXP package.
```

Not sure if it's really about Adobe Extension Manager update, but something have changed ...

**Comment by Lilipi** [comment]
Is there something about certificate ?

**Comment by Lilipi** [comment]
Could you please tell me what url you use to timestamp zxp packaging ? We passed to summer time last week-end. Could it be a problem with that ?

**Comment by Lilipi** [comment]
Sorry about that, it was a problem with our certificate.

**Comment by fcamarlinghi** [comment]
No worries. :) I'll go ahead and close the issue then. Feel free to reopen it or open a new one should you come across other problems.

As a side note: the Adobe Extension Manager should not really be used because it's outdated (at least, I think it is, please feel free to correct me!) and might produce unreliable results. Right now there are two ways of checking/installing packages that I know of: the Adobe Exchange service itself and the ExMan command line tool you can find on the Adobe website.
