### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by bluecyclone** [fcamarlinghi/grunt-cep#27]
I have cep extension for the premiere and I want to be auto-update could you please guide me how to do that ?

**Comment by fcamarlinghi** [comment]
_grunt-cep_ is a tool that helps with the packaging process, auto-updating an installed extension is outside its scope. You should consider using Adobe Exchange or a custom solution for that, but the more appropriate place to ask for help would be the [Adobe forums](https://forums.adobe.com/community/creative_cloud/add-ons/extensions).
