### ISSUE TITLE
Debug jsx files.

### ISSUE THREAD

**Issue by rvignacio** [fcamarlinghi/grunt-cep#3]
Hello, is it possible to debug jsx files? Or is it out of the scope of this grunt plugin?

Thanks,

**Comment by fcamarlinghi** [comment]
No, the plugin only helps with testing and packaging extensions. You'll need to use the [Adobe Extendscript Toolkit](https://creative.adobe.com/products/estk), which is available as a free download from Creative Cloud, to be able to debug Extendscript files.

**Comment by rvignacio** [comment]
Great! Thanks for the answer
