### ISSUE TITLE
'Missing DispatchInfo detected' when trying to use debug mode

### ISSUE THREAD

**Issue by danabrey** [fcamarlinghi/grunt-cep#30]
I'm trying to use the `cep:debug` task to debug my extension, but am hitting the following error, taken from: `CEP8-IDSN.log`

```
2018-10-22 14:32:30:153 : DEBUG Found extension with id 'acme.indesign.exporter.panel.debug'
2018-10-22 14:32:30:156 : DEBUG Missing DispatchInfo detected
2018-10-22 14:32:30:158 : INFO  Removing extension with id 'acme.indesign.exporter.panel.debug' because it is incomplete
```

I'm using InDesign 2018 v13.1

Packaging the extension using `cep:release` and installing it results in the extension being loaded as expected. 

When comparing the two `manifest.xml` files - one from the installed packaged extension in _C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\acme.indesign.exporter.panel_ and one from the debug-mode extension in _%APPDATA%\Roaming\Adobe\CEP\extensions\acme.indesign.exporter.panel.debug_ - the only difference is the `.debug` suffix on the extension ID and the ` (debug)` suffix on the extension name.

Any ideas what may be causing this?

**Comment by fcamarlinghi** [comment]
Hello, unfortunately I don't currently have access to InDesign 2018, and my experience developing extensions for InDesign is quite limited. The `.debug` suffix in the extension ID shouldn't cause any problems though AFAIK.

I tried to reproduce the issue on a trial version of InDesign 2019, but the extension installed and run correctly in both debug and release configurations. The extension I used in my tests was created using the [grunt-init-cep](https://github.com/fcamarlinghi/grunt-init-cep) template. Can you please try that as-well and see if you end up with the same error?

**Comment by danabrey** [comment]
PEBKAC error, I'm afraid. I had the extension id hard-coded in one place, which meant that the extension wasn't being added as expected. Apologies, thanks for taking the time to respond.
