### ISSUE TITLE
update npm to 3.0

### ISSUE THREAD

**Issue by jDmacD** [fcamarlinghi/grunt-cep#4]
Hi,
Can this be done?
For compatibility with [grunt-init-cep](https://github.com/fcamarlinghi/grunt-init-cep)

**Comment by fcamarlinghi** [comment]
Hello, yeah sorry about that! I got everything ready a couple of months ago for a new NPM version, but then I totally forgot to actually publish it. It [should be up](https://www.npmjs.com/package/grunt-cep) by now, thanks for reminding me! :)
