### ISSUE TITLE
Host Binary Name

### ISSUE THREAD

**Issue by pcdeshmukh** [fcamarlinghi/grunt-cep#45]
Hello,
Not sure of all the hosts but following two are wrong for mac binary name.
https://github.com/fcamarlinghi/grunt-cep/blob/91174328eb875353bca829d4e95390450d7010c3/tasks/lib/hosts.json#L24
https://github.com/fcamarlinghi/grunt-cep/blob/91174328eb875353bca829d4e95390450d7010c3/tasks/lib/hosts.json#L72

Thanks,
Paresh

**Comment by fcamarlinghi** [comment]
Thanks for reporting the issue, binary names should be fixed in 0.7.1.
